import * as https from "https";
import * as fs from "fs";
import * as path from "path";
import AdmZip from "adm-zip";

const SCHEMA_URL =
        "https://schema.cloudformation.us-east-1.amazonaws.com/CloudformationSchema.zip";
const OUT_FILE = path.join(__dirname, "../src/data/resources.ts");

interface CfnProperty {
        type: string;
        required: boolean;
        description: string;
}

interface CfnResource {
        description: string;
        attributes: string[];
        properties: Record<string, CfnProperty>;
}

function download(url: string): Promise<Buffer> {
        return new Promise((resolve, reject) => {
                https.get(url, (res) => {
                        const chunks: Buffer[] = [];
                        res.on("data", (chunk) => chunks.push(chunk));
                        res.on("end", () => resolve(Buffer.concat(chunks)));
                        res.on("error", reject);
                }).on("error", reject);
        });
}

function resolveType(value: any): string {
        if (!value) return "string";
        if (value.type) {
                if (Array.isArray(value.type)) return value.type[0];
                return value.type;
        }
        if (value.$ref) return "object";
        if (value.anyOf || value.oneOf) return "string";
        return "string";
}

function parseSchema(raw: any): CfnResource | null {
        try {
                const typeName: string = raw.typeName;
                if (!typeName || !typeName.startsWith("AWS::")) return null;

                const description: string = raw.description || `${typeName} resource`;
                const required: string[] = raw.required || [];
                const rawProps = raw.properties || {};

                const properties: Record<string, CfnProperty> = {};
                for (const [propName, propValue] of Object.entries(rawProps)) {
                        const prop = propValue as any;
                        properties[propName] = {
                                type: resolveType(prop),
                                required: required.includes(propName),
                                description: prop.description || "",
                        };
                }

                // Extract !GetAtt attributes from readOnlyProperties
                // They look like "/properties/Arn" — we just want "Arn"
                const attributes: string[] = [];
                if (Array.isArray(raw.readOnlyProperties)) {
                        for (const attrPath of raw.readOnlyProperties) {
                                const parts = attrPath.split("/");
                                // Only include top level attributes, skip nested ones
                                if (parts.length === 3) {
                                        attributes.push(parts[parts.length - 1]);
                                }
                        }
                }

                return { description, attributes, properties };
        } catch {
                return null;
        }
}

async function main() {
        console.log("Downloading CloudFormation schema...");
        const buffer = await download(SCHEMA_URL);

        console.log("Extracting...");
        const zip = new AdmZip(buffer);
        const entries = zip.getEntries();

        console.log(`Found ${entries.length} schema files`);

        const resources: Record<string, CfnResource> = {};

        for (const entry of entries) {
                if (!entry.entryName.endsWith(".json")) continue;

                try {
                        const content = entry.getData().toString("utf8");
                        const raw = JSON.parse(content);
                        const parsed = parseSchema(raw);

                        if (parsed && raw.typeName) {
                                resources[raw.typeName] = parsed;
                        }
                } catch {
                        // skip malformed files
                }
        }

        const count = Object.keys(resources).length;
        console.log(`Parsed ${count} resource types`);

        const lines: string[] = [];
        lines.push(`// AUTO-GENERATED by scripts/fetch-schema.ts`);
        lines.push(`// Source: ${SCHEMA_URL}`);
        lines.push(`// Do not edit manually — run npm run fetch-schema to regenerate`);
        lines.push(``);
        lines.push(`export interface CfnProperty {`);
        lines.push(`    type: string;`);
        lines.push(`    required: boolean;`);
        lines.push(`    description: string;`);
        lines.push(`}`);
        lines.push(``);
        lines.push(`export interface CfnResource {`);
        lines.push(`    description: string;`);
        lines.push(`    attributes: string[];`);
        lines.push(`    properties: Record<string, CfnProperty>;`);
        lines.push(`}`);
        lines.push(``);
        lines.push(`export const resources: Record<string, CfnResource> = {`);

        for (const [typeName, resource] of Object.entries(resources)) {
                const escapedDesc = resource.description
                        .replace(/`/g, "'")
                        .replace(/\\/g, "\\\\");
                lines.push(`    ${JSON.stringify(typeName)}: {`);
                lines.push(`        description: ${JSON.stringify(escapedDesc)},`);
                lines.push(`        attributes: ${JSON.stringify(resource.attributes)},`);
                lines.push(`        properties: {`);

                for (const [propName, prop] of Object.entries(resource.properties)) {
                        const escapedPropDesc = prop.description
                                .replace(/`/g, "'")
                                .replace(/\\/g, "\\\\");
                        lines.push(
                                `            ${JSON.stringify(propName)}: { type: ${JSON.stringify(prop.type)}, required: ${prop.required}, description: ${JSON.stringify(escapedPropDesc)} },`,
                        );
                }

                lines.push(`        }`);
                lines.push(`    },`);
        }

        lines.push(`};`);

        const output = lines.join("\n");

        fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
        fs.writeFileSync(OUT_FILE, output, "utf8");

        console.log(`Written to ${OUT_FILE}`);
}

main().catch((err) => {
        console.error("Failed:", err);
        process.exit(1);
});
